service:
  name: middleware-test

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-middleware

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  apiGateway:
    minimumCompressionSize: 1024

functions:

  # Users
  getAllUsers:
    handler:
      - ./middleware.middlewareFunc
      - ./user.getFunc
    events:
      - http:
          method: GET
          path: users

